### ISSUE TITLE
add .wav fortmat 

### ISSUE THREAD

**Issue by EzioFenix** [amirmaula/rtx-acapella#1]
could you add compatibility with .wav is that going to mp3 is a lot of loss of quality, please :D

**Comment by amirldn** [comment]
Yes, I can add that feature and will get to work on it soon for the next update 👍

**Comment by amirldn** [comment]
So I've been doing a bit of digging and noticed that adding WAV support just isn't feasible due to the fact it would mean I would have to rewrite most of my code since the library I have used for the input song has no WAV compatibility. Also, when processing through the RTX program, it would remove any of the quality increase I achieve by changing the input to WAV anyways so there isn't much point here. Sorry for this! I may add support for other audio codecs like FLAC since the library, mutagen, supports it.

**Comment by EzioFenix** [comment]
If you can add support for FLAC, it would be perfect, the grace is that it is a better container than mp3.

Thanks for the help bro


De: Amir Maula <notifications@github.com>
Enviado el: domingo, 16 de agosto de 2020 06:14 p. m.
Para: amirmaula/rtx-acapella <rtx-acapella@noreply.github.com>
CC: EzioFenix <vaitor_victor@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [amirmaula/rtx-acapella] add .wav fortmat (#1)


So I've been doing a bit of digging and noticed that adding WAV support just isn't feasible due to the fact it would mean I would have to rewrite most of my code since the library I have used for the input song has no WAV compatibility. Also, when processing through the RTX program, it would remove any of the quality increase I achieve by changing the input to WAV anyways so there isn't much point here. Sorry for this! I may add support for other audio codecs like FLAC since the library, mutagen, supports it.

**Comment by amirldn** [comment]
FLAC Support has been added!
