### ISSUE TITLE
Asynchronous tasks

### ISSUE THREAD

**Issue by COLOR-SKY** [amirmaula/rtx-acapella#3]
Since all the task sessions use the same audio device, it seems impossible to run all of them simultaneously. Any idea?

**Comment by amirldn** [comment]
Hi,

I'm a little bit confused by what you mean by task sessions? Are you talking about both the VB AUX input and output device?

**Comment by COLOR-SKY** [comment]
When running two programs simultaneously, the outputs will overlap.
This is because both programs(tasks) are using the same VB device.
I'm wondering if it is possible to assign each process a unique device for recording.

**Comment by amirldn** [comment]
Ahh okay that makes sense now. Currently the program only supports one media file at a time. This is because it is not possible to have two instances of the RTX Voice program so even if multiple VB device's existed, you would need another process of RTX Voice to handle the other VB device. Unless there was a way to execute another RTX Voice process this is not currently possible.
